function SelResp(OpcSel)
{
    if(OpcSel==1)
    {
        document.getElementById('RespTip1').style.display='block';
        document.getElementById('RespTip2').style.display='none';
        document.getElementById('RespTip3').style.display='none';
        document.getElementById('RespTip4').style.display='none';
        document.getElementById('RespTip5').style.display='none';
        document.getElementById('RespTip6').style.display='none';
        document.getElementById('RespTip7').style.display='none';
    }

    if(OpcSel==2)
    {
        document.getElementById('RespTip1').style.display='none';
        document.getElementById('RespTip2').style.display='block';
        document.getElementById('RespTip3').style.display='none';
        document.getElementById('RespTip4').style.display='none';
        document.getElementById('RespTip5').style.display='none';
        document.getElementById('RespTip6').style.display='none';
        document.getElementById('RespTip7').style.display='none';
    }

    if(OpcSel==3)
    {
        document.getElementById('RespTip1').style.display='none';
        document.getElementById('RespTip2').style.display='none';
        document.getElementById('RespTip3').style.display='block';
        document.getElementById('RespTip4').style.display='none';
        document.getElementById('RespTip5').style.display='none';
        document.getElementById('RespTip6').style.display='none';
        document.getElementById('RespTip7').style.display='none';
    }

    if(OpcSel==4)
    {
        document.getElementById('RespTip1').style.display='none';
        document.getElementById('RespTip2').style.display='none';
        document.getElementById('RespTip3').style.display='none';
        document.getElementById('RespTip4').style.display='block';
        document.getElementById('RespTip5').style.display='none';
        document.getElementById('RespTip6').style.display='none';
        document.getElementById('RespTip7').style.display='none';
    }

    if(OpcSel==5)
    {
        document.getElementById('RespTip1').style.display='none';
        document.getElementById('RespTip2').style.display='none';
        document.getElementById('RespTip3').style.display='none';
        document.getElementById('RespTip4').style.display='none';
        document.getElementById('RespTip5').style.display='block';
        document.getElementById('RespTip6').style.display='none';
        document.getElementById('RespTip7').style.display='none';
    }

    if(OpcSel==6)
    {
        document.getElementById('RespTip1').style.display='none';
        document.getElementById('RespTip2').style.display='none';
        document.getElementById('RespTip3').style.display='none';
        document.getElementById('RespTip4').style.display='none';
        document.getElementById('RespTip5').style.display='none';
        document.getElementById('RespTip6').style.display='block';
        document.getElementById('RespTip7').style.display='none';
    }

    if(OpcSel==7)
    {
        document.getElementById('RespTip1').style.display='none';
        document.getElementById('RespTip2').style.display='none';
        document.getElementById('RespTip3').style.display='none';
        document.getElementById('RespTip4').style.display='none';
        document.getElementById('RespTip5').style.display='none';
        document.getElementById('RespTip6').style.display='none';
        document.getElementById('RespTip7').style.display='block';
    }
}