-- MySQL Script generated by MySQL Workbench
-- Thu Sep 20 02:35:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proy_educatorium
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proy_educatorium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proy_educatorium` DEFAULT CHARACTER SET utf8 ;
USE `proy_educatorium` ;

-- -----------------------------------------------------
-- Table `proy_educatorium`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Grado` (
  `ID_Grado` INT NOT NULL AUTO_INCREMENT,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`ID_Grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Tipo_Apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Tipo_Apoyo` (
  `ID_Tipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Apoyo` (
  `ID_Apoyo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ruta` VARCHAR(50) NOT NULL,
  `Tipo_Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Apoyo`),
  INDEX `fk_Apoyo_Tipo_Apoyo1_idx` (`Tipo_Apoyo_ID` ASC),
  CONSTRAINT `fk_Apoyo_Tipo_Apoyo1`
    FOREIGN KEY (`Tipo_Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Apoyo` (`ID_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Escuela` (
  `ID_Escuela` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Num_Esc` INT NOT NULL,
  PRIMARY KEY (`ID_Escuela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Tipo_Pal_Rec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Tipo_Pal_Rec` (
  `ID_Tip_Key` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Keyword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tip_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Estudiante` (
  `ID_Estudiante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Pat` VARCHAR(45) NOT NULL,
  `Ape_Mat` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Keyword` VARCHAR(45) NOT NULL,
  `Tip_Key_ID` INT NOT NULL,
  `Grado_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  `Escuela_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Estudiante`),
  INDEX `fk_Estudiante_Grado_idx` (`Grado_ID` ASC),
  INDEX `fk_Estudiante_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Estudiante_Escuela1_idx` (`Escuela_ID` ASC),
  INDEX `fk_Estudiante_Tipo_Pal_Rec_idx` (`Tip_Key_ID` ASC),
  CONSTRAINT `fk_Estudiante_Grado`
    FOREIGN KEY (`Grado_ID`)
    REFERENCES `proy_educatorium`.`Grado` (`ID_Grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Escuela1`
    FOREIGN KEY (`Escuela_ID`)
    REFERENCES `proy_educatorium`.`Escuela` (`ID_Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Tip_Pal_Rec`
    FOREIGN KEY (`Tip_Key_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Pal_Rec` (`ID_Tip_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Profesor` (
  `ID_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Pat` VARCHAR(45) NOT NULL,
  `Ape_Mat` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Keyword` VARCHAR(45) NOT NULL,
  `Tip_Key_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Profesor`),
  INDEX `fk_Profesor_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Profesor_Tip_Pal_Rec_idx` (`Tip_Key_ID` ASC),
  CONSTRAINT `fk_Profesor_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Tip_Pal_Rec`
    FOREIGN KEY (`Tip_Key_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Pal_Rec` (`ID_Tip_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Padre` (
  `ID_Padre` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Pat` VARCHAR(45) NOT NULL,
  `Ape_Mat` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Keyword` VARCHAR(45) NOT NULL,
  `Tip_Key_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Padre`),
  INDEX `fk_Padre_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Padre_Tip_Pal_Rec_idx` (`Tip_Key_ID` ASC),
  CONSTRAINT `fk_Padre_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padre_Tip_Pal_Rec`
    FOREIGN KEY (`Tip_Key_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Pal_Rec` (`ID_Tip_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Materia` (
  `ID_Materia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Grado_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Materia`),
  INDEX `fk_Materia_Grado1_idx` (`Grado_ID` ASC),
  CONSTRAINT `fk_Materia_Grado1`
    FOREIGN KEY (`Grado_ID`)
    REFERENCES `proy_educatorium`.`Grado` (`ID_Grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Curso` (
  `ID_Curso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Msg_Bien` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Materia_ID` INT NOT NULL,
  `Profesor_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Curso`),
  INDEX `fk_Curso_Materia1_idx` (`Materia_ID` ASC),
  INDEX `fk_Curso_Profesor1_idx` (`Profesor_ID` ASC),
  CONSTRAINT `fk_Curso_Materia1`
    FOREIGN KEY (`Materia_ID`)
    REFERENCES `proy_educatorium`.`Materia` (`ID_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Profesor1`
    FOREIGN KEY (`Profesor_ID`)
    REFERENCES `proy_educatorium`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Cuestionario` (
  `ID_Cuestionario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Curso_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Cuestionario`),
  INDEX `fk_Cuestionario_Curso1_idx` (`Curso_ID` ASC),
  CONSTRAINT `fk_Cuestionario_Curso1`
    FOREIGN KEY (`Curso_ID`)
    REFERENCES `proy_educatorium`.`Curso` (`ID_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Pregunta` (
  `ID_Pregunta` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Num_Preg_Cues` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Cuestionario_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Pregunta`),
  INDEX `fk_Pregunta_Cuestionario1_idx` (`Cuestionario_ID` ASC),
  INDEX `fk_Pregunta_Apoyo1_idx` (`Apoyo_ID` ASC),
  CONSTRAINT `fk_Pregunta_Cuestionario1`
    FOREIGN KEY (`Cuestionario_ID`)
    REFERENCES `proy_educatorium`.`Cuestionario` (`ID_Cuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Alternativa` (
  `ID_Alternativa` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NOT NULL,
  `Estatus` VARCHAR(45) NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Alternativa`),
  INDEX `fk_Alternativa_Pregunta1_idx` (`Pregunta_ID` ASC),
  CONSTRAINT `fk_Alternativa_Pregunta1`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `proy_educatorium`.`Pregunta` (`ID_Pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Mat_Profe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Mat_Profe` (
  `ID_Mat_Profe` INT NOT NULL AUTO_INCREMENT,
  `Materia_ID` INT NOT NULL,
  `Profe_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Mat_Profe`),
  INDEX `fk_Mat_Profe_Materia1_idx` (`Materia_ID` ASC),
  INDEX `fk_Mat_Profe_Profesor1_idx` (`Profe_ID` ASC),
  CONSTRAINT `fk_Mat_Profe_Materia1`
    FOREIGN KEY (`Materia_ID`)
    REFERENCES `proy_educatorium`.`Materia` (`ID_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mat_Profe_Profesor1`
    FOREIGN KEY (`Profe_ID`)
    REFERENCES `proy_educatorium`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' 			  	 ';


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Profe_Escu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Profe_Escu` (
  `ID_Profe_Escu` INT NOT NULL AUTO_INCREMENT,
  `Profesor_ID` INT NOT NULL,
  `Escuela_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Profe_Escu`),
  INDEX `fk_Profe_Escu_Profesor1_idx` (`Profesor_ID` ASC),
  INDEX `fk_Profe_Escu_Escuela1_idx` (`Escuela_ID` ASC),
  CONSTRAINT `fk_Profe_Escu_Profesor1`
    FOREIGN KEY (`Profesor_ID`)
    REFERENCES `proy_educatorium`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profe_Escu_Escuela1`
    FOREIGN KEY (`Escuela_ID`)
    REFERENCES `proy_educatorium`.`Escuela` (`ID_Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Curso_Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Curso_Estudiante` (
  `ID_Curso_Estudiante` INT NOT NULL AUTO_INCREMENT,
  `Curso_ID` INT NOT NULL,
  `Estudiante_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Curso_Estudiante`),
  INDEX `fk_Curso_Estudiante_Curso1_idx` (`Curso_ID` ASC),
  INDEX `fk_Curso_Estudiante_Estudiante1_idx` (`Estudiante_ID` ASC),
  CONSTRAINT `fk_Curso_Estudiante_Curso1`
    FOREIGN KEY (`Curso_ID`)
    REFERENCES `proy_educatorium`.`Curso` (`ID_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_ID`)
    REFERENCES `proy_educatorium`.`Estudiante` (`ID_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Resp_Altern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Resp_Altern` (
  `ID_Resp_Altern` INT NOT NULL AUTO_INCREMENT,
  `Alternativa_ID` INT NOT NULL,
  `Estudiante_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Resp_Altern`),
  INDEX `fk_Resp_Altern_Alternativa1_idx` (`Alternativa_ID` ASC),
  INDEX `fk_Resp_Altern_Estudiante1_idx` (`Estudiante_ID` ASC),
  CONSTRAINT `fk_Resp_Altern_Alternativa1`
    FOREIGN KEY (`Alternativa_ID`)
    REFERENCES `proy_educatorium`.`Alternativa` (`ID_Alternativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resp_Altern_Estudiante1`
    FOREIGN KEY (`Estudiante_ID`)
    REFERENCES `proy_educatorium`.`Estudiante` (`ID_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Apoyo_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Apoyo_Curso` (
  `ID_Apoyo_Curso` INT NOT NULL AUTO_INCREMENT,
  `Apoyo_ID` INT NOT NULL,
  `Curso_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Apoyo_Curso`),
  INDEX `fk_Apoyo_Curso_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Apoyo_Curso_Curso1_idx` (`Curso_ID` ASC),
  CONSTRAINT `fk_Apoyo_Curso_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoyo_Curso_Curso1`
    FOREIGN KEY (`Curso_ID`)
    REFERENCES `proy_educatorium`.`Curso` (`ID_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Padre_Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Padre_Estudiante` (
  `ID_Familiar` INT NOT NULL AUTO_INCREMENT,
  `Padre_ID` INT NOT NULL,
  `Estudiante_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Familiar`),
  INDEX `fk_Padre_Estudiante_Padre1_idx` (`Padre_ID` ASC),
  INDEX `fk_Padre_Estudiante_Estudiante1_idx` (`Estudiante_ID` ASC),
  CONSTRAINT `fk_Padre_Estudiante_Padre1`
    FOREIGN KEY (`Padre_ID`)
    REFERENCES `proy_educatorium`.`Padre` (`ID_Padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padre_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_ID`)
    REFERENCES `proy_educatorium`.`Estudiante` (`ID_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO grado (Valor) VALUES (1);
INSERT INTO grado (Valor) VALUES (2);
INSERT INTO grado (Valor) VALUES (3);

INSERT INTO materia (Nombre,Grado_ID) VALUES ('Espa 1',1);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Mate 1',1);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Biolo',1);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Geogra',1);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Ingl 1',1);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('CyE 11',1);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Hist 11',1);

INSERT INTO materia (Nombre,Grado_ID) VALUES ('Espa 2',2);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Mate 2',2);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Fisica',2);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Ingl 2',2);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('CyE 12',2);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Hist 12',2);

INSERT INTO materia (Nombre,Grado_ID) VALUES ('Espa 3',3);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Mate 3',3);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Quimic',3);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Ingl 3',3);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('CyE 2',3);
INSERT INTO materia (Nombre,Grado_ID) VALUES ('Hist 2',3);