-- MySQL Script generated by MySQL Workbench
-- Thu Nov 15 08:31:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proy_educatorium
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proy_educatorium
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `proy_educatorium` DEFAULT CHARACTER SET utf8 ;
USE `proy_educatorium` ;

-- -----------------------------------------------------
-- Table `proy_educatorium`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Grado` (
  `ID_Grado` INT NOT NULL AUTO_INCREMENT,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`ID_Grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Tipo_Apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Tipo_Apoyo` (
  `ID_Tipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Apoyo` (
  `ID_Apoyo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ruta` VARCHAR(56) NOT NULL,
  `Tipo_Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Apoyo`),
  INDEX `fk_Apoyo_Tipo_Apoyo1_idx` (`Tipo_Apoyo_ID` ASC),
  CONSTRAINT `fk_Apoyo_Tipo_Apoyo1`
    FOREIGN KEY (`Tipo_Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Apoyo` (`ID_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Tipo_Esc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Tipo_Esc` (
  `ID_Tipo_Esc` INT NOT NULL AUTO_INCREMENT,
  `TipoEscuela` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_Tipo_Esc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Escuela` (
  `ID_Escuela` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` INT NOT NULL,
  `Num_Esc` INT NOT NULL,
  PRIMARY KEY (`ID_Escuela`),
  INDEX `fk_Escuela_Tipo_Esc_idx` (`Tipo` ASC),
  CONSTRAINT `fk_Escuela_Tipo_Esc`
    FOREIGN KEY (`Tipo`)
    REFERENCES `proy_educatorium`.`Tipo_Esc` (`ID_Tipo_Esc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Tipo_Pal_Rec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Tipo_Pal_Rec` (
  `ID_Tip_Key` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Keyword` VARCHAR(46) NOT NULL,
  PRIMARY KEY (`ID_Tip_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Estudiante` (
  `ID_Estudiante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Pat` VARCHAR(45) NOT NULL,
  `Ape_Mat` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Keyword` VARCHAR(46) NOT NULL,
  `Tip_Key_ID` INT NOT NULL,
  `Grado_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  `Escuela_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Estudiante`),
  INDEX `fk_Estudiante_Grado_idx` (`Grado_ID` ASC),
  INDEX `fk_Estudiante_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Estudiante_Escuela1_idx` (`Escuela_ID` ASC),
  INDEX `fk_Estudiante_Tipo_Pal_Rec_idx` (`Tip_Key_ID` ASC),
  CONSTRAINT `fk_Estudiante_Grado`
    FOREIGN KEY (`Grado_ID`)
    REFERENCES `proy_educatorium`.`Grado` (`ID_Grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Escuela1`
    FOREIGN KEY (`Escuela_ID`)
    REFERENCES `proy_educatorium`.`Escuela` (`ID_Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Tip_Pal_Rec`
    FOREIGN KEY (`Tip_Key_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Pal_Rec` (`ID_Tip_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Profesor` (
  `ID_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Pat` VARCHAR(45) NOT NULL,
  `Ape_Mat` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Keyword` VARCHAR(46) NOT NULL,
  `Tip_Key_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Profesor`),
  INDEX `fk_Profesor_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Profesor_Tip_Pal_Rec_idx` (`Tip_Key_ID` ASC),
  CONSTRAINT `fk_Profesor_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Tip_Pal_Rec`
    FOREIGN KEY (`Tip_Key_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Pal_Rec` (`ID_Tip_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Padre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Padre` (
  `ID_Padre` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ape_Pat` VARCHAR(45) NOT NULL,
  `Ape_Mat` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Keyword` VARCHAR(46) NOT NULL,
  `Tip_Key_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Padre`),
  INDEX `fk_Padre_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Padre_Tip_Pal_Rec_idx` (`Tip_Key_ID` ASC),
  CONSTRAINT `fk_Padre_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padre_Tip_Pal_Rec`
    FOREIGN KEY (`Tip_Key_ID`)
    REFERENCES `proy_educatorium`.`Tipo_Pal_Rec` (`ID_Tip_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Materia` (
  `ID_Materia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Grado_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Materia`),
  INDEX `fk_Materia_Grado1_idx` (`Grado_ID` ASC),
  CONSTRAINT `fk_Materia_Grado1`
    FOREIGN KEY (`Grado_ID`)
    REFERENCES `proy_educatorium`.`Grado` (`ID_Grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Curso` (
  `ID_Curso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Msg_Bien` VARCHAR(100) NULL,
  `Password` VARCHAR(45) NULL,
  `Materia_ID` INT NOT NULL,
  `Profesor_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Curso`),
  INDEX `fk_Curso_Materia1_idx` (`Materia_ID` ASC),
  INDEX `fk_Curso_Profesor1_idx` (`Profesor_ID` ASC),
  CONSTRAINT `fk_Curso_Materia1`
    FOREIGN KEY (`Materia_ID`)
    REFERENCES `proy_educatorium`.`Materia` (`ID_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Profesor1`
    FOREIGN KEY (`Profesor_ID`)
    REFERENCES `proy_educatorium`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Cuestionario` (
  `ID_Cuestionario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Curso_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Cuestionario`),
  INDEX `fk_Cuestionario_Curso1_idx` (`Curso_ID` ASC),
  CONSTRAINT `fk_Cuestionario_Curso1`
    FOREIGN KEY (`Curso_ID`)
    REFERENCES `proy_educatorium`.`Curso` (`ID_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Tipo_Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Tipo_Pregunta` (
  `ID_Tipo_Preg` INT NOT NULL AUTO_INCREMENT,
  `TipoPregunta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Tipo_Preg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Pregunta` (
  `ID_Pregunta` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NOT NULL,
  `Tipo` INT NOT NULL,
  `Num_Preg_Cues` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Cuestionario_ID` INT NOT NULL,
  `Apoyo_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Pregunta`),
  INDEX `fk_Pregunta_Cuestionario1_idx` (`Cuestionario_ID` ASC),
  INDEX `fk_Pregunta_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Pregunta_Tipo_Pregunta_idx` (`Tipo` ASC),
  CONSTRAINT `fk_Pregunta_Cuestionario1`
    FOREIGN KEY (`Cuestionario_ID`)
    REFERENCES `proy_educatorium`.`Cuestionario` (`ID_Cuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_Tipo_Pregunta`
    FOREIGN KEY (`Tipo`)
    REFERENCES `proy_educatorium`.`Tipo_Pregunta` (`ID_Tipo_Preg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Estatus_Resp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Estatus_Resp` (
  `ID_Status` INT NOT NULL AUTO_INCREMENT,
  `Condicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Alternativa` (
  `ID_Alternativa` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  `Estatus_Prof` INT NOT NULL,
  PRIMARY KEY (`ID_Alternativa`),
  INDEX `fk_Alternativa_Pregunta1_idx` (`Pregunta_ID` ASC),
  INDEX `fk_Alternativa_Status_idx` (`Estatus_Prof` ASC),
  CONSTRAINT `fk_Alternativa_Pregunta1`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `proy_educatorium`.`Pregunta` (`ID_Pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alternativa_Status`
    FOREIGN KEY (`Estatus_Prof`)
    REFERENCES `proy_educatorium`.`Estatus_Resp` (`ID_Status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Mat_Profe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Mat_Profe` (
  `ID_Mat_Profe` INT NOT NULL AUTO_INCREMENT,
  `Materia_ID` INT NOT NULL,
  `Profe_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Mat_Profe`),
  INDEX `fk_Mat_Profe_Materia1_idx` (`Materia_ID` ASC),
  INDEX `fk_Mat_Profe_Profesor1_idx` (`Profe_ID` ASC),
  CONSTRAINT `fk_Mat_Profe_Materia1`
    FOREIGN KEY (`Materia_ID`)
    REFERENCES `proy_educatorium`.`Materia` (`ID_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mat_Profe_Profesor1`
    FOREIGN KEY (`Profe_ID`)
    REFERENCES `proy_educatorium`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' 			  	 ';


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Profe_Escu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Profe_Escu` (
  `ID_Profe_Escu` INT NOT NULL AUTO_INCREMENT,
  `Profesor_ID` INT NOT NULL,
  `Escuela_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Profe_Escu`),
  INDEX `fk_Profe_Escu_Profesor1_idx` (`Profesor_ID` ASC),
  INDEX `fk_Profe_Escu_Escuela1_idx` (`Escuela_ID` ASC),
  CONSTRAINT `fk_Profe_Escu_Profesor1`
    FOREIGN KEY (`Profesor_ID`)
    REFERENCES `proy_educatorium`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profe_Escu_Escuela1`
    FOREIGN KEY (`Escuela_ID`)
    REFERENCES `proy_educatorium`.`Escuela` (`ID_Escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Curso_Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Curso_Estudiante` (
  `ID_Curso_Estudiante` INT NOT NULL AUTO_INCREMENT,
  `Curso_ID` INT NOT NULL,
  `Estudiante_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Curso_Estudiante`),
  INDEX `fk_Curso_Estudiante_Curso1_idx` (`Curso_ID` ASC),
  INDEX `fk_Curso_Estudiante_Estudiante1_idx` (`Estudiante_ID` ASC),
  CONSTRAINT `fk_Curso_Estudiante_Curso1`
    FOREIGN KEY (`Curso_ID`)
    REFERENCES `proy_educatorium`.`Curso` (`ID_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_ID`)
    REFERENCES `proy_educatorium`.`Estudiante` (`ID_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Resp_Estudi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Resp_Estudi` (
  `ID_Resp_Estudi` INT NOT NULL AUTO_INCREMENT,
  `Estudiante_ID` INT NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  `Calificacion` INT NOT NULL,
  PRIMARY KEY (`ID_Resp_Estudi`),
  INDEX `fk_Resp_Altern_Estudiante1_idx` (`Estudiante_ID` ASC),
  INDEX `fk_Resp_Estudi_Pregunta_idx` (`Pregunta_ID` ASC),
  CONSTRAINT `fk_Resp_Estudi_Estudiante1`
    FOREIGN KEY (`Estudiante_ID`)
    REFERENCES `proy_educatorium`.`Estudiante` (`ID_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resp_Estudi_Pregunta`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `proy_educatorium`.`Pregunta` (`ID_Pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Apoyo_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Apoyo_Curso` (
  `ID_Apoyo_Curso` INT NOT NULL AUTO_INCREMENT,
  `Apoyo_ID` INT NOT NULL,
  `Curso_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Apoyo_Curso`),
  INDEX `fk_Apoyo_Curso_Apoyo1_idx` (`Apoyo_ID` ASC),
  INDEX `fk_Apoyo_Curso_Curso1_idx` (`Curso_ID` ASC),
  CONSTRAINT `fk_Apoyo_Curso_Apoyo1`
    FOREIGN KEY (`Apoyo_ID`)
    REFERENCES `proy_educatorium`.`Apoyo` (`ID_Apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoyo_Curso_Curso1`
    FOREIGN KEY (`Curso_ID`)
    REFERENCES `proy_educatorium`.`Curso` (`ID_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Padre_Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Padre_Estudiante` (
  `ID_Familiar` INT NOT NULL AUTO_INCREMENT,
  `Padre_ID` INT NOT NULL,
  `Estudiante_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Familiar`),
  INDEX `fk_Padre_Estudiante_Padre1_idx` (`Padre_ID` ASC),
  INDEX `fk_Padre_Estudiante_Estudiante1_idx` (`Estudiante_ID` ASC),
  CONSTRAINT `fk_Padre_Estudiante_Padre1`
    FOREIGN KEY (`Padre_ID`)
    REFERENCES `proy_educatorium`.`Padre` (`ID_Padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padre_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_ID`)
    REFERENCES `proy_educatorium`.`Estudiante` (`ID_Estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Desc_Bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Desc_Bloques` (
  `ID_Bloque` INT NOT NULL AUTO_INCREMENT,
  `Desc_Bloque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Bloque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Altern_Rel_Cols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Altern_Rel_Cols` (
  `ID_Altern_Rel_Cols` INT NOT NULL AUTO_INCREMENT,
  `Alter_a_Rel` VARCHAR(45) NOT NULL,
  `Inciso_Right` VARCHAR(45) NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  `Bloque` INT NOT NULL,
  PRIMARY KEY (`ID_Altern_Rel_Cols`),
  INDEX `fk_Altern_Rel_Pregunta_idx` (`Pregunta_ID` ASC),
  INDEX `fk_Bloque` (`Bloque` ASC),
  CONSTRAINT `fk_Altern_Rel_Pregunta`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `proy_educatorium`.`Pregunta` (`ID_Pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Altern_Rel_Desc_Bloques`
    FOREIGN KEY (`Bloque`)
    REFERENCES `proy_educatorium`.`Desc_Bloques` (`ID_Bloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Altern_Ord_Sel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Altern_Ord_Sel` (
  `ID_Altern_Ord` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NOT NULL,
  `Pos_Corre` INT NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  `Bloque` INT NOT NULL,
  PRIMARY KEY (`ID_Altern_Ord`),
  INDEX `fk_Altern_Ord_Preg_idx` (`Pregunta_ID` ASC),
  INDEX `fk_Altern_Ord_Bloque_Ord_idx` (`Bloque` ASC),
  CONSTRAINT `fk_Altern_Ord_Preg`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `proy_educatorium`.`Pregunta` (`ID_Pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Altern_Ord_Bloque_Ord`
    FOREIGN KEY (`Bloque`)
    REFERENCES `proy_educatorium`.`Desc_Bloques` (`ID_Bloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_educatorium`.`Altern_Compl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proy_educatorium`.`Altern_Compl` (
  `ID_Alternativa` INT NOT NULL AUTO_INCREMENT,
  `Contenido` VARCHAR(45) NOT NULL,
  `Pert_Lista` INT NOT NULL,
  `Pregunta_ID` INT NOT NULL,
  `Estatus_Prof` INT NOT NULL,
  PRIMARY KEY (`ID_Alternativa`),
  INDEX `fk_Alternativa_Pregunta1_idx` (`Pregunta_ID` ASC),
  INDEX `fk_Alternativa_Status_idx` (`Estatus_Prof` ASC),
  CONSTRAINT `fk_Alternativa_Pregunta10`
    FOREIGN KEY (`Pregunta_ID`)
    REFERENCES `proy_educatorium`.`Pregunta` (`ID_Pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alternativa_Status0`
    FOREIGN KEY (`Estatus_Prof`)
    REFERENCES `proy_educatorium`.`Estatus_Resp` (`ID_Status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
